grafana:
  adminUser: admin
  adminPassword: admin

  persistence:
    enabled: true
 
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.local.com
  sidecar:
    dashboards:
      enabled: true

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.prometheus.svc.cluster.local
          isDefault: true
          editable: true

global:
  dashboards:
    cluster-dashboard: true