grafana:
  adminUser: admin
  adminPassword: admin

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.local.com
  sidecar:
    dashboards:
      enabled: true

global:
  dashboards:
    argocd-dashboard: true