apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets
  namespace: external-secrets
  labels:
    app: external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete"]