replicaCount: 1

image:
  repository: ghcr.io/external-secrets/kubernetes-external-secrets
  tag: 8.5.5
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

podSecurityContext: {}
securityContext: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}